### ISSUE TITLE
Overriden request method  in restclient_ext breaks SSL options in newer rest-client libraries

### ISSUE THREAD

**Issue by pdilung** [abenari/rbovirt#73] opened 2015-03-01 11:17 UTC

**Comment by pdilung** [comment] 2015-03-01 11:31
The overriden `RestClient::Request#request` does not seem to honor SSL options `OVIRT::Client` costructor, when newer REST client is used. At least these options are not handled properly:
 * `ca_no_verify`
 * `ca_cert_file`

Commenting `require "restclient_ext/request"` fixes the problem.

Setting `SSL_CERT_FILE=<a_path_to_certfile>` environment variable works regardless the monkey patch is loaded or not, thus this might be used as a workaround in some cases.

My setup:
* OS
   * Kernel: 3.10.0-123.20.1.el7.x86_64
   * Distro: CentOS Linux release 7.0.1406 (Core)
* Ruby
   * Interpreter: ruby 2.0.0p353 (2013-11-22) [x86_64-linux]
   * rbovirt: 0.0.35
   * rest-client: 1.7.3

@abenari Is it possible to get a fix for this? I remember some discussions about this monkey patch in the past. Is it still necessary to have it in the upstream?

**Comment by abenari** [comment] 2015-03-01 12:15
@pdilung the issue is that rest-client 1.7.x is not ruby 1.8.7 compatible.
If we will have a code that uses the monkey-patch just for rest-client prior to 1.7, I think that would be best.
A different approach can be to have this fix and release rbovirt 0.1.0, this way projects that depends on rbovirt and and ruby 1.8.7, aka [foreman](https://github.com/theforeman/foreman), can lock the gem version to 0.0.x.

**Comment by pdilung** [comment] 2015-03-01 12:55
@abenari Does the 1st approach mean to check for rest-client version in `rbovirt.rb`?

**Comment by abenari** [comment] 2015-03-03 12:01
Pull request #45 is OK as long as we also release in version 0.1.0 and set  required_ruby_version in the gemspec.

**Comment by abenari** [comment] 2015-03-03 12:20
fixed in 951fdc5a3d5337eceafef0ddf8fd3d16817d0cb9

**Closed by abenari** 2015-03-03 12:20 UTC

**Comment by pdilung** [comment] 2015-03-03 12:38
@abenari  :+1:
